# Generated by Django 5.2.7 on 2025-11-09 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0003_phoneotp_delete_userverifycode_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='measurement_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='real_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.AddField(
            model_name='product',
            name='measurement',
            field=models.CharField(choices=[('gr', 'Gram'), ('kg', 'Kilogram'), ('pc', 'Piece'), ('l', 'Litre'), ('ml', 'Milliliter')], default='gr', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bf', 'Breakfast'), ('lu', 'Lunch'), ('dn', 'Dinner'), ('all', 'All')], db_index=True, default='all', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_uz',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='users.device')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
