# Generated by Django 5.2.7 on 2025-11-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
